services:
  wine-app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.config/earthengine:/root/.config/earthengine
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    command: flask --app app run --host 0.0.0.0 --port 5000 --debug
